### GET all countries (public)
GET {{host}}/countries
Accept: application/json

###

### POST create new country (USER or ADMIN)
POST {{host}}/countries
Content-Type: application/json
Authorization: Bearer {{token_user}}

{
  "name": "Test Country"
}

###

### PUT update country (USER or ADMIN)
PUT {{host}}/countries/2
Content-Type: application/json
Authorization: Bearer {{token_user}}

{
  "name": "Updated Country"
}

###

### DELETE country (ADMIN only)
DELETE {{host}}/countries/2
Authorization: Bearer {{token_admin}}

###