// ===============================
// Country.java (Entity)
// ===============================

package cz.mendelu.ea.domain.country;

import cz.mendelu.ea.domain.happiness.Happiness;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.*;

import java.util.HashSet;
import java.util.Set;

/**
 * Entity representing a country.
 * <p>
 * - Has a unique name (max 100 chars).
 * - Each country can have multiple happiness records (see {@link Happiness}).
 * - Relationship: OneToMany (Country to Happiness).
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Country {

    /** Primary key, autogenerated. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Country name, must be unique and not blank. */
    @NotBlank
    @Size(max = 100)
    @Column(unique = true)
    private String name;

    /**
     * All happiness records for this country.
     * Cascade and orphanRemoval ensure correct state on delete/update.
     */
    @Builder.Default
    @OneToMany(mappedBy = "country", cascade = CascadeType.ALL, orphanRemoval = true)
    private Set<Happiness> happinessRecords = new HashSet<>();

    /**
     * Create a country with given name.
     */
    public Country(String name) {
        this.name = name;
        this.happinessRecords = new HashSet<>();
    }

    /**
     * Attach a new happiness record.
     */
    public void addHappinessRecord(Happiness record) {
        happinessRecords.add(record);
        record.setCountry(this);
    }

    /**
     * Remove a happiness record.
     */
    public void removeHappinessRecord(Happiness record) {
        happinessRecords.remove(record);
        record.setCountry(null);
    }
}
